language: cpp
dist: xenial

matrix:
  fast_finish: true
  include:
    - env: target_os=mac target_cpu=x64
      os: osx
      osx_image: xcode10.1
    - env: target_os=linux target_cpu=x64
#    - env: target_os=android target_cpu=arm
#    - env: target_os=android target_cpu=arm64
#    - env: target_os=android target_cpu=x86
#    - env: target_os=android target_cpu=x64

branches:
  only:
    - master

before_install:

  - if [ $target_os == "linux" ]; then
      sudo apt-get install -qq python3;
      export compiler=gcc;
    else
      export compiler=clang;
    fi

script:

  #- ./build-posix.sh -p $target_os -a $target_cpu

  #- python3 package.py --os=$target_os --cpu=$target_cpu --compiler=$compiler
  - touch webrtc-datachannel-*.tar.gz

before_deploy:
  - mkdir builds
  - mv webrtc-datachannel-*.tar.gz builds

deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY
  secret_access_key: $S3_SECRET_KEY
  bucket: $S3_BUCKET
  skip_cleanup: true
  local_dir: builds
  on:
    all_branches: true
