version: "{build}"

branches:
  only:
    - master

image: Visual Studio 2017
platform: x64

build_script:

  - build-win.bat

  - C:\Python37-x64\python.exe package.py --os=win --cpu=x64 --compiler=msvc

  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON -G "Visual Studio 15 2017 Win64" ..
  - cmake --build . --config Release -- -verbosity:minimal
  - cd ..

  # commented because it just blocks in appveyor
  #- build\examples\Release\loopback_test.exe

artifacts:
  - path: webrtc-datachannel-*.tar.gz
    name: builds

deploy:
  provider: S3
  access_key_id: $(S3_ACCESS_KEY)
  secret_access_key: $(S3_SECRET_KEY)
  bucket: $(S3_BUCKET)
  artifact: builds
